### ISSUE TITLE
백엔드 회의사항 정하기

### ISSUE THREAD

**Issue by kor-Chipmunk** [mash-up-kr/Dionysos-Backend#1]
백엔드 회의사항 정하기

**Comment by kor-Chipmunk** [comment]
## 안건 정하기

- [x] 깃 플로우 규칙 정하기
- [x] 도메인 모델 정리하기
- [x] DB 설계 정하기
- [ ] 작업들 이슈 발행하고 각자 할당하기

**Comment by kor-Chipmunk** [comment]
## 깃 플로우 규칙 정하기
- [x] 커밋 작성방법 정하기
- [x] 이 레포에서 할 지 포크따서 할 지
- [x] 브랜치 명 정하기

**Comment by kor-Chipmunk** [comment]
## 1. 이 레포에서 할 지 포크따서 할 지
매쉬업 레포로 하고 브랜치 관리를 빡세게 하기

**Comment by kor-Chipmunk** [comment]
## 2. 브랜치명 정하기
- `develop` 브랜치를 만들고 작업한 것들을 취합
- `master` 브랜치에 PR 되는 순간 CI/CD 배포
- `feature/{이슈번호}_{작업명}` 으로 기능 작업할 때 쓰기 ( 예시. `feature/1_create_model` )

**Comment by kor-Chipmunk** [comment]
## 3. 커밋 작성 방법 정하기

- [ ]  한글로 쓰기 ( ex. `#1. 로그인 추가` )
- [ ] 영어로 쓰기 ( ex. `#1. Add login feature` )
- [x] `feat`, `chore`, `fix` ( ex. `feat. #1. Add login feature` )

### 형식을 어떻게 하면 좋을까?
- [x]  커밋명에 이슈 번호를 적고 해당 이슈에 자세한 구현 내용을 적기
- [x] 한글로 적기
- [ ] 이모지 활용법 ( `:hammer: Fix it` )

### 최종 커밋명 예시
- `feat: #1. 로그인 기능 추가`
- `fix: #2. 로그인 기능 수정`
- `chore: #3. 로그인 설정파일 추가`
- `docs`: (changes to the documentation)
- `style`: (formatting, missing semi colons, etc; no production code change)
- `refactor`: (refactoring production code, eg. renaming a variable)
- `test`: (adding missing tests, refactoring tests; no production code change)

참고 자료 : https://gist.github.com/joshbuchea/6f47e86d2510bce28f8e7f42ae84c716. 
https://www.conventionalcommits.org/en/v1.0.0-beta.2/

**Comment by kor-Chipmunk** [comment]
## 1차 배포. 도메인 모델 & DB 정리하기

1. 사용자
2. 일기
3. 시간 기록
3.1. 하루의 기준을 새벽 6시 기준

### 1. 사용자
- 다른 잘하는 사람들한테 물어보기
- 토큰 테이블도 어떻게 만들어야 하는지 물어보기
- 역할은 STRING 으로 넣기

### 2. 일기
- fk_user : FK
- picture_url : VARCHAR
- content : TEXT
- created_date : DATETIME

S3 연동 방법 : https://jojoldu.tistory.com/300

### 3. 누적 시간 기록
- fk_user : FK
- duration  : INT
- date : DATETIME

Q. 오프라인일 때 어떻게 데이터를 쌓고 언제 보내줄지? 프론트에서 캐싱해서 나중에 연결되면 한 번에 보내주기

**Comment by kor-Chipmunk** [comment]
## 프로젝트 구조 어떻게 하면 좋을지

- [x] 일단은 도메인 모델로 나누고 controller, dto, model 이런식으로 나눔
- [ ] 일단은 controller, dto, model 로 먼저 나누고, 그 다음에 도메인별로 나눔
